### PR TITLE
Migrate copying upstream AspectJ binaries + sources from Ant to Maven

### LINKED ISSUE #8: Remove AspectJ source and class files from AJDT repository
Similar to how AspectJ now has a clean dependency on JDT Core instead of keeping a binary copy inside the SCM, AJDT should remove the copied class and source files from AspectJ, namely
* AspectJ runtime,
* AspectJ tools (compiler),
* AspectJ weaver,

and instead depend on the corresponding libraries, which are all public anyway. At the moment, Ant script [org.aspectj.ajde/build-aj-jars.xml](https://github.com/eclipse/ajdt/blob/9f7a0fee27b49ae845019ad5f993e47325c14c5d/org.aspectj.ajde/build-aj-jars.xml) copies and unzips them, then they have to be committed to Git. The Ant script requires an AspectJ working directory and information about its location.

I have not analysed the build process any further yet, but I think the only thing that happens later is that the libraries are enriched with some OSGi meta information and then re-packaged into JAR archives again, only to be included in the AJDT installation package.  I think that it should be possible to generate this meta information and add it to the existing JAR files on the fly using some appropriate Maven plugin.

It might also be worth investigating if it would somehow be possible **not** to include the libraries into AJDT but instead reference and dynamically download them. Maybe we can even add a settings dialogue in order to enable independent AspectJ version upgrades or project-specific switches without necessarily having to release a new AJDT version. That would save us cycles and make users more flexible. @aclement, WDYT?

@aeisenberg, I would like to hear your opinion about the last idea as well.

---

I used a tool called [Grand](https://ant-grand.github.io/Grand/grand.html) in order to graphically represent the Ant targets from _build-aj-jars.xml_:

image

Other than the main goal `plugin jars` which copies the classes and sources from the 3 main AspectJ artifacts, the AJDT build does not use the other Ant targets anymore, because we build with Maven. I just wanted to document it a little bit, before I remove than Ant script in favour of a pure Maven solution.

### PR DESCRIPTION
**Pull request by kriegaex**
Remove AspectJ source and class files from AJDT repository. Instead, use Maven Dependency Plugin in order to download them from a repository and unpack them dynamically.

There is also a new Maven Clean configuration for each of the 3 affected modules, taking care of deleting the files during `mvn clean`.

**TODO:** For now, the files are unpacked into the same directories _classes_ and _source_, directly inside the corresponding module directory. It would be better to unpack them to a _target_ subdirectory.

Delete _build-aj-jars.xml_ and _aspectjlib.properties_, because we no longer need them. The target AspectJ version can now be set using Maven property `aspectj.version`.

Fixes #8.

### CODE REVIEW

**Comment by kriegaex** [comment]
@aclement, @aeisenberg: I noticed that the big commit I had pushed before was difficult to review on GitHub's web UI, because it contained 6,000+ files, only half of which were loaded. Even after excluding deleted files from the view, GitHub would not reload the remaining ones. Therefore, I split the original commit in 2 commits, one smaller one containing the main changes and a huge one only containing the 6k deleted AspectJ class and source files. Then I force-pushed the PR. Now you can comfortably review the first commit.

**Review by aeisenberg — COMMENTED** [review]
I really don't have enough context here since I never worked on this part of the build. My thinking is that if this is producing plugin bundles that are installable and runnable, then it's probably fine.

**Comment by kriegaex** [comment]
Sorry, I committed some small cosmetic commits unrelated to the issue at hand onto this branch.

**Comment by kriegaex** [comment]
> if this is producing plugin bundles that are installable and runnable, then it's probably fine

I did not test extensively, but the bundles are indeed installable and runnable. I guess I am going to merge it, also update branch `e423` and issue a Jenkins build, updating the update site with signed artifacts. I guess that sooner or later someone will complain, if anything is broken due to this change. But I do not expect it to be, and I kind of like AJDT with 6,000+ files less in its belly. Branch switches are quicker now, too.

**Review by aeisenberg — APPROVED** [review]
Go for it. Again...I don't have the background to know if this change is sufficient, but it seems low risk given the state of the project.

**Pull request merged**
